# Generated by Django 3.1.3 on 2020-11-04 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_activacion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('temp_min', models.FloatField()),
                ('temp_max', models.FloatField()),
                ('luz_min', models.FloatField()),
                ('luz_max', models.FloatField()),
                ('ph_min', models.FloatField()),
                ('ph_max', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('magnitud', models.FloatField()),
                ('tipo_magnitud', models.CharField(max_length=50)),
                ('id_cultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greentower.cultivo')),
            ],
        ),
        migrations.AddField(
            model_name='cultivo',
            name='id_planta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='greentower.planta'),
        ),
    ]
