# Generated by Django 3.1.3 on 2020-11-04 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greentower', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cultivo',
            options={'ordering': ('fecha_activacion',)},
        ),
        migrations.AlterModelOptions(
            name='medida',
            options={'ordering': ('-datetime',)},
        ),
        migrations.AlterModelOptions(
            name='planta',
            options={'ordering': ('nombre',)},
        ),
    ]
