# Generated by Django 3.1.3 on 2020-11-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greentower', '0002_auto_20201104_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medida',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
