# Generated by Django 3.1.3 on 2020-11-05 15:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('greentower', '0006_auto_20201105_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medida',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
